const express=require('express')
const app=express()
const path=require('path')
const publicDir = path.join(__dirname,'../Public')
const db=require('./Database/db')
const UserRouter=require('./Routes/User.Routes')
const RentFloorRouter=require('./Routes/RentFloor.Routes')
const PaymentRouter=require('./Routes/Payment.Routes')
const FAQRouter=require('./Routes/FAQ.Routes')
const morgan=require('morgan')
const cors=require('cors')
app.use(express.static(publicDir));
app.use(cors())
app.use(express.json())
app.use(morgan('tiny')) 
app.use('/user',UserRouter)
app.use('/rentfloor',RentFloorRouter)
app.use('/khaltipayment',PaymentRouter)
app.use('/faq',FAQRouter)
module.exports=app